let REPORT_STATE = {
  COMPLETE: 0,
  INCOMPLETE: 1,
};

let REPORT_TYPE = {
  VIOLATION: 0,
  REGISTER_BOARD: 1,
  COMMENTS: 2,
  TROUBLESHOOTING: 3,
};

let REQUEST_TYPE = {
  LICENSE: 0,
  EDIT: 1,
};

let REQUEST_STATE_TYPE = {
  INCOMPLETE: 0,
  COMPLETE: 1,
  DECLINE: 2,
};

module.exports = { REPORT_STATE, REPORT_TYPE, REQUEST_STATE_TYPE };
